name: Fetch and Commit Weather Data

on:
  schedule:
    - cron: '0 12 * * *'  # This runs the workflow every day at 12:00 PM UTC
  workflow_dispatch:  # You can also manually trigger this workflow

jobs:
  fetch_weather_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install axios simple-git

      - name: Fetch and Commit Weather Data
        run: |
          node fetchWeatherAndCommit.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
